-- Active: 1664945899270@@sonky.myasustor.com@3306@udemy
-- CREATE TABLE
--   students (
--     id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
--     first_name VARCHAR(50)
--   )
-- CREATE TABLE
--   papers (
--     title VARCHAR(50),
--     grade VARCHAR(50),
--     student_id INT,
--     FOREIGN KEY (student_id) REFERENCES students (id)
--   )
-- SELECT first_name, title, grade FROM students JOIN papers ON students.id = papers.student_id ORDER BY grade DESC;
-- SELECT first_name, IFNULL(title, 'MISSING'), IFNULL(grade, 0) FROM students LEFT JOIN papers ON students.id = papers.student_id;
-- SELECT first_name, IFNULL(AVG(grade), 0) AS average FROM students LEFT JOIN papers ON students.id = papers.student_id GROUP BY students.id ORDER BY average DESC;
-- SELECT
--   first_name,
--   IFNULL (AVG(grade), 0) AS average,
--   CASE
--     WHEN AVG(grade) >= 75 THEN 'PASSING'
--     ELSE 'FAILING'
--   END AS passing_status
-- FROM
--   students
--   LEFT JOIN papers ON students.id = papers.student_id
-- GROUP BY
--   students.id
-- ORDER BY
--   average DESC;